### ISSUE TITLE
Out of bounds access

### ISSUE THREAD

**Issue by Hodorcoder** [ZeusNoTZues/Competetive-Programming-Q-A#1]
https://github.com/ZeusNoTZues/Competetive-Programming-Q-A/blob/master/Problems-and-Solutions/Easy/CodeForces/%23721A%20One-dimensional%20Japanese%20Crossword.cpp

    if (Encrypted [i] == 'B')
			Count++;
    elif (Encrypted [i - 1] == 'B')

What if the first character read is 'W'? i -1 will be -1

   4
   WWWW

**Comment by ZeusNoTZues** [comment]
Thanks for your input **Hodorcoder**! You can find the fix [here](https://github.com/ZeusNoTZues/Competetive-Programming-Q-A/blob/master/Problems-and-Solutions/Easy/CodeForces/%23721A%20One-dimensional%20Japanese%20Crossword.cpp).

**Comment by Hodorcoder** [comment]
I don't know how I noticed it
